package com.example.lbos.repository;

import com.example.lbos.entity.FleetOwner;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class FleetOwnerRepositoryTest {

    @Autowired
    private FleetOwnerRepository repository;

    private FleetOwner entity;
    private final UUID cityId = UUID.randomUUID();

    @BeforeEach
    void setUp() {
        entity = new FleetOwner();
        entity.setUserAccountId(UUID.fromString("11111111-1111-1111-1111-111111111111"));
        entity.setCityId(cityId);
        entity.setBusinessName("ABC Logistics");
        entity.setProfileStatus("VERIFIED");
        entity.setOwnerStatus("ACTIVE");
    }

    @Test
    void saveTest() {
        FleetOwner saved = repository.save(entity);
        assertNotNull(saved.getFleetOwnerId());
    }

    @Test
    void findByCityIdTest() {
        repository.save(entity);
        List<FleetOwner> list = repository.findByCityId(cityId);
        assertFalse(list.isEmpty());
    }

    @Test
    void findByOwnerStatusTest() {
        repository.save(entity);
        List<FleetOwner> list = repository.findByOwnerStatus("ACTIVE");
        assertFalse(list.isEmpty());
    }

    @Test
    void findByProfileStatusTest() {
        repository.save(entity);
        List<FleetOwner> list = repository.findByProfileStatus("VERIFIED");
        assertFalse(list.isEmpty());
    }

    @Test
    void findByBusinessNameTest() {
        repository.save(entity);
        List<FleetOwner> list = repository.findByBusinessNameContainingIgnoreCase("logistics");
        assertFalse(list.isEmpty());
    }

    @Test
    void testAutoGeneratedUUID() {
        FleetOwner newEntity = new FleetOwner();
        newEntity.setUserAccountId(UUID.randomUUID());
        newEntity.setCityId(cityId);
        newEntity.setBusinessName("Auto Gen Fleet");
        newEntity.setProfileStatus("VERIFIED");
        newEntity.setOwnerStatus("ACTIVE");

        FleetOwner saved1 = repository.save(newEntity);
        assertNotNull(saved1.getFleetOwnerId());

        FleetOwner newEntity2 = new FleetOwner();
        newEntity2.setUserAccountId(UUID.randomUUID());
        newEntity2.setCityId(cityId);
        newEntity2.setBusinessName("Auto Gen Fleet 2");
        newEntity2.setProfileStatus("VERIFIED");
        newEntity2.setOwnerStatus("ACTIVE");

        FleetOwner saved2 = repository.save(newEntity2);
        assertNotNull(saved2.getFleetOwnerId());
        assertNotEquals(saved1.getFleetOwnerId(), saved2.getFleetOwnerId());
    }
}
