package com.example.lbos.repository;

import com.example.lbos.entity.Retailer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class RetailerRepositoryTest {

    @Autowired
    private RetailerRepository retailerRepository;

    private Retailer retailer;
    private final UUID cityId = UUID.fromString("33333333-3333-3333-3333-333333333333");

    @BeforeEach
    void setUp() {
        retailer = new Retailer();
        retailer.setUserAccountId(UUID.fromString("11111111-1111-1111-1111-111111111111"));
        retailer.setOperationsManagerId(UUID.fromString("22222222-2222-2222-2222-222222222222"));
        retailer.setCityId(cityId);
        retailer.setLongitude(new BigDecimal("78.1234567"));
        retailer.setLatitude(new BigDecimal("11.2345678"));
        retailer.setBusinessName("ABC Retail Store");
        retailer.setRegistrationNumber("REG12345");
        retailer.setGstNumber("33ABCDE1234F1Z5");
        retailer.setRetailerStatus("ACTIVE");
    }

    @Test
    void saveRetailerTest() {
        Retailer savedRetailer = retailerRepository.save(retailer);
        assertNotNull(savedRetailer);
        assertNotNull(savedRetailer.getRetailerId());
    }

    @Test
    void findRetailerByIdTest() {
        Retailer savedRetailer = retailerRepository.save(retailer);
        Optional<Retailer> found = retailerRepository.findById(savedRetailer.getRetailerId());
        assertTrue(found.isPresent());
        assertEquals(savedRetailer.getBusinessName(), found.get().getBusinessName());
    }

    @Test
    void findAllRetailersTest() {
        retailerRepository.save(retailer);
        List<Retailer> retailers = retailerRepository.findAll();
        assertFalse(retailers.isEmpty());
    }

    @Test
    void findByCityIdTest() {
        retailerRepository.save(retailer);
        List<Retailer> retailers = retailerRepository.findByCityId(cityId);
        assertFalse(retailers.isEmpty());
        assertEquals(cityId, retailers.get(0).getCityId());
    }

    @Test
    void findByRetailerStatusTest() {
        retailerRepository.save(retailer);
        List<Retailer> retailers = retailerRepository.findByRetailerStatus("ACTIVE");
        assertFalse(retailers.isEmpty());
        assertEquals("ACTIVE", retailers.get(0).getRetailerStatus());
    }

    @Test
    void findByBusinessNameTest() {
        retailerRepository.save(retailer);
        List<Retailer> retailers = retailerRepository.findByBusinessNameContainingIgnoreCase("abc");
        assertFalse(retailers.isEmpty());
    }

    @Test
    void testAutoGeneratedUUID() {
        Retailer newEntity = new Retailer();
        newEntity.setUserAccountId(UUID.randomUUID());
        newEntity.setCityId(UUID.randomUUID());
        newEntity.setBusinessName("Auto Gen Store");
        newEntity.setRetailerStatus("ACTIVE");

        Retailer saved1 = retailerRepository.save(newEntity);
        assertNotNull(saved1.getRetailerId());

        Retailer newEntity2 = new Retailer();
        newEntity2.setUserAccountId(UUID.randomUUID());
        newEntity2.setCityId(UUID.randomUUID());
        newEntity2.setBusinessName("Auto Gen Store 2");
        newEntity2.setRetailerStatus("ACTIVE");

        Retailer saved2 = retailerRepository.save(newEntity2);
        assertNotNull(saved2.getRetailerId());
        assertNotEquals(saved1.getRetailerId(), saved2.getRetailerId());
    }

    @Test
    void deleteRetailerTest() {
        Retailer savedRetailer = retailerRepository.save(retailer);
        retailerRepository.deleteById(savedRetailer.getRetailerId());
        Optional<Retailer> found = retailerRepository.findById(savedRetailer.getRetailerId());
        assertTrue(found.isEmpty());
    }
}
