package com.example.lbos.repository;

import com.example.lbos.entity.VerificationDocument;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class VerificationDocumentRepositoryTest {

    @Autowired
    private VerificationDocumentRepository repository;

    private VerificationDocument entity;
    private final UUID verificationQueueId = UUID.randomUUID();

    @BeforeEach
    void setUp() {
        entity = new VerificationDocument();
        entity.setVerificationQueueId(verificationQueueId);
        entity.setDocumentTypeName("DRIVING_LICENSE");
        entity.setVersionNumber(1);
        entity.setFileName("retailer123.pdf");
        entity.setContentType("application/pdf");
        entity.setFileSizeBytes(2048L);
        entity.setExpiryDate(LocalDate.of(2030, 12, 31));
        entity.setDocumentStatus("PENDING");
        entity.setIsCurrentVersion(true);
        entity.setCreatedAt(OffsetDateTime.now());
        entity.setUpdatedAt(OffsetDateTime.now());
    }

    @Test
    void saveTest() {
        VerificationDocument saved = repository.save(entity);
        assertNotNull(saved.getDocumentId());
    }

    @Test
    void findByVerificationQueueIdTest() {
        repository.save(entity);
        List<VerificationDocument> list = repository.findByVerificationQueueId(verificationQueueId);
        assertFalse(list.isEmpty());
    }

    @Test
    void findByDocumentStatusTest() {
        repository.save(entity);
        List<VerificationDocument> list = repository.findByDocumentStatus("PENDING");
        assertFalse(list.isEmpty());
    }

    @Test
    void findByDocumentTypeNameTest() {
        repository.save(entity);
        List<VerificationDocument> list = repository.findByDocumentTypeName("DRIVING_LICENSE");
        assertFalse(list.isEmpty());
    }

    @Test
    void findByIsCurrentVersionTest() {
        repository.save(entity);
        List<VerificationDocument> list = repository.findByIsCurrentVersion(true);
        assertFalse(list.isEmpty());
    }

    @Test
    void findByVerificationQueueIdAndIsCurrentVersionTest() {
        repository.save(entity);
        List<VerificationDocument> list = repository.findByVerificationQueueIdAndIsCurrentVersion(verificationQueueId, true);
        assertFalse(list.isEmpty());
    }

    @Test
    void testAutoGeneratedUUID() {
        VerificationDocument newEntity = new VerificationDocument();
        newEntity.setVerificationQueueId(verificationQueueId);
        newEntity.setDocumentTypeName("PASSPORT");
        newEntity.setVersionNumber(1);
        newEntity.setFileName("pass1.pdf");
        newEntity.setDocumentStatus("PENDING");
        newEntity.setIsCurrentVersion(true);
        newEntity.setCreatedAt(OffsetDateTime.now());
        newEntity.setUpdatedAt(OffsetDateTime.now());

        VerificationDocument saved1 = repository.save(newEntity);
        assertNotNull(saved1.getDocumentId());

        VerificationDocument newEntity2 = new VerificationDocument();
        newEntity2.setVerificationQueueId(verificationQueueId);
        newEntity2.setDocumentTypeName("ID_CARD");
        newEntity2.setVersionNumber(1);
        newEntity2.setFileName("id1.pdf");
        newEntity2.setDocumentStatus("PENDING");
        newEntity2.setIsCurrentVersion(true);
        newEntity2.setCreatedAt(OffsetDateTime.now());
        newEntity2.setUpdatedAt(OffsetDateTime.now());

        VerificationDocument saved2 = repository.save(newEntity2);
        assertNotNull(saved2.getDocumentId());
        assertNotEquals(saved1.getDocumentId(), saved2.getDocumentId());
    }
}
