package com.example.lbos.repository;

import com.example.lbos.entity.VerificationQueue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class VerificationQueueRepositoryTest {

    @Autowired
    private VerificationQueueRepository repository;

    private VerificationQueue entity;
    private final UUID subjectId = UUID.randomUUID();
    private final UUID submittedByAccountId = UUID.randomUUID();

    @BeforeEach
    void setUp() {
        entity = new VerificationQueue();
        entity.setSubjectType("RETAILER");
        entity.setSubjectId(subjectId);
        entity.setIsActive(true);
        entity.setSubmittedByAccountId(submittedByAccountId);
        entity.setVerificationStatus("PENDING");
        entity.setCreatedAt(OffsetDateTime.now());
        entity.setUpdatedAt(OffsetDateTime.now());
    }

    @Test
    void saveTest() {
        VerificationQueue saved = repository.save(entity);
        assertNotNull(saved.getVerificationQueueId());
    }

    @Test
    void findBySubjectIdTest() {
        repository.save(entity);
        List<VerificationQueue> list = repository.findBySubjectId(subjectId);
        assertFalse(list.isEmpty());
    }

    @Test
    void findBySubjectTypeTest() {
        repository.save(entity);
        List<VerificationQueue> list = repository.findBySubjectType("RETAILER");
        assertFalse(list.isEmpty());
    }

    @Test
    void findByVerificationStatusTest() {
        repository.save(entity);
        List<VerificationQueue> list = repository.findByVerificationStatus("PENDING");
        assertFalse(list.isEmpty());
    }

    @Test
    void findByIsActiveTest() {
        repository.save(entity);
        List<VerificationQueue> list = repository.findByIsActive(true);
        assertFalse(list.isEmpty());
    }

    @Test
    void testAutoGeneratedUUID() {
        VerificationQueue newEntity = new VerificationQueue();
        newEntity.setSubjectType("RETAILER");
        newEntity.setSubjectId(subjectId);
        newEntity.setIsActive(true);
        newEntity.setSubmittedByAccountId(UUID.randomUUID());
        newEntity.setVerificationStatus("PENDING");
        newEntity.setCreatedAt(OffsetDateTime.now());
        newEntity.setUpdatedAt(OffsetDateTime.now());

        VerificationQueue saved1 = repository.save(newEntity);
        assertNotNull(saved1.getVerificationQueueId());

        VerificationQueue newEntity2 = new VerificationQueue();
        newEntity2.setSubjectType("FLEET_OWNER");
        newEntity2.setSubjectId(subjectId);
        newEntity2.setIsActive(true);
        newEntity2.setSubmittedByAccountId(UUID.randomUUID());
        newEntity2.setVerificationStatus("PENDING");
        newEntity2.setCreatedAt(OffsetDateTime.now());
        newEntity2.setUpdatedAt(OffsetDateTime.now());

        VerificationQueue saved2 = repository.save(newEntity2);
        assertNotNull(saved2.getVerificationQueueId());
        assertNotEquals(saved1.getVerificationQueueId(), saved2.getVerificationQueueId());
    }

    @Test
    void findBySubmittedByAccountIdTest() {
        repository.save(entity);
        List<VerificationQueue> list = repository.findBySubmittedByAccountId(submittedByAccountId);
        assertFalse(list.isEmpty());
    }
}
