package com.lbos.commercecustomer.service.impl; import com.lbos.commercecustomer.dto.request.ProductRequest;import com.lbos.commercecustomer.dto.response.*;import com.lbos.commercecustomer.entity.*;import com.lbos.commercecustomer.enums.InventoryStatus;import com.lbos.commercecustomer.enums.ProductStatus;import com.lbos.commercecustomer.exception.*;import com.lbos.commercecustomer.mapper.CommerceMapper;import com.lbos.commercecustomer.repository.*;import com.lbos.commercecustomer.service.CatalogueService;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*; @Service public class CatalogueServiceImpl implements CatalogueService {private final ProductRepository repo;private final ProductCategoryRepository cats;private final CustomerWishlistItemRepository wish;private final CustomerCartRepository carts;private final CustomerReviewRepository reviews;private final ContextSupport ctx;private final CommerceMapper map;public CatalogueServiceImpl(ProductRepository r,ProductCategoryRepository c,CustomerWishlistItemRepository w,CustomerCartRepository ca,CustomerReviewRepository rv,ContextSupport x,CommerceMapper m){repo=r;cats=c;wish=w;carts=ca;reviews=rv;ctx=x;map=m;}private UUID retailer(){return ctx.retailer().retailerId();}private Product owned(Long id){return repo.findByIdAndRetailerId(id,retailer()).orElseThrow(()->new ResourceNotFoundException("Product not found"));}private void apply(Product product,ProductRequest r,Long id){String sku=r.sku().trim().toUpperCase();boolean dup=id==null?repo.existsByRetailerIdAndSkuIgnoreCase(retailer(),sku):repo.existsByRetailerIdAndSkuIgnoreCaseAndIdNot(retailer(),sku,id);if(dup)throw new DuplicateResourceException("SKU already exists");var category=cats.findById(r.categoryId()).orElseThrow(()->new ResourceNotFoundException("Category not found"));boolean unchangedCategory=product.getCategory()!=null&&category.getId().equals(product.getCategory().getId());if(category.getStatus()!=com.lbos.commercecustomer.enums.CategoryStatus.ACTIVE&&!unchangedCategory)throw new BusinessValidationException("Category '"+category.getName()+"' is not active - choose an active category");copyFields(product,sku,category,r);}

  /** The product fields a create/update sets - shared with the retailer bulk upload so both go through the same assignment. */
  public static void copyFields(Product product,String sku,ProductCategory category,ProductRequest r){product.setName(r.name().trim());product.setSku(sku);product.setCategory(category);product.setUnitPrice(r.unitPrice());product.setStatus(r.status());product.setDescription(r.description().trim());product.setLowStockThreshold(r.lowStockThreshold());product.setWeightKg(r.weightKg()==null?Product.DEFAULT_WEIGHT_KG:r.weightKg());}@Transactional public ProductResponse create(ProductRequest r){if(r.stock()==null)throw new BusinessValidationException("stock is required when creating a product");var product=new Product();product.setRetailerId(retailer());product.setStock(r.stock());apply(product,r,null);return map.product(repo.save(product));}@Transactional(readOnly=true) public ProductResponse get(Long id){return map.product(owned(id));}

  /**
   * q/categoryId/status are applied as WHERE clauses at the DB level via ProductSpecifications,
   * scoped to the retailer's own catalogue. inventoryStatus is also pushed down at the DB level
   * (see ProductSpecifications.inventoryStatus) rather than kept as an in-memory post-filter,
   * since it can be expressed as a comparison against stock/lowStockThreshold - so pagination
   * metadata (totalElements/totalPages) always reflects the full filtered result set, not just
   * the page returned.
   */
  @Transactional(readOnly=true) public PageResponse<ProductResponse> search(String q,Long cat,String status,String inv,int p,int z){
    ProductStatus statusFilter=parseEnum(ProductStatus.class,status);
    InventoryStatus inventoryFilter=parseEnum(InventoryStatus.class,inv);
    Specification<Product> spec=Specification.allOf(
        ProductSpecifications.retailerId(retailer()),
        ProductSpecifications.nameOrSkuContains(q),
        ProductSpecifications.categoryId(cat),
        ProductSpecifications.status(statusFilter),
        ProductSpecifications.inventoryStatus(inventoryFilter),
        ProductSpecifications.fetchCategory());
    var productPage=repo.findAll(spec,PageRequest.of(p,z));
    return new PageResponse<>(productPage.map(map::product).getContent(),p,z,productPage.getTotalElements(),productPage.getTotalPages());
  }

  private <E extends Enum<E>> E parseEnum(Class<E> type,String raw){if(raw==null||raw.isBlank())return null;try{return Enum.valueOf(type,raw.trim().toUpperCase());}catch(IllegalArgumentException ex){throw new BusinessValidationException("Unsupported value '"+raw+"' for "+type.getSimpleName());}}

  @Transactional public ProductResponse update(Long id,ProductRequest r){var product=owned(id);apply(product,r,id);return map.product(repo.save(product));}@Transactional public void delete(Long id){var product=owned(id);boolean referenced=wish.existsByProduct_Id(id)||carts.existsByProduct_Id(id)||reviews.existsByProduct_Id(id);if(referenced)throw new BusinessValidationException("Product is referenced by customer data");repo.delete(product);}@Transactional public ProductResponse duplicate(Long id){var source=owned(id);var copy=new Product();copy.setRetailerId(retailer());copy.setCategory(source.getCategory());copy.setName(source.getName()+" Copy");copy.setDescription(source.getDescription());copy.setUnitPrice(source.getUnitPrice());copy.setStatus(ProductStatus.DRAFT);copy.setStock(0);String base=source.getSku()+"-COPY",sku=base;int suffix=2;while(repo.existsByRetailerIdAndSkuIgnoreCase(retailer(),sku))sku=base+(suffix++);copy.setSku(sku);return map.product(repo.save(copy));}@Transactional(readOnly=true) public CatalogueSummaryResponse summary(){var products=repo.findByRetailerId(retailer(),Pageable.unpaged()).getContent();return new CatalogueSummaryResponse(products.size(),products.stream().filter(product->ProductStatus.ACTIVE.equals(product.getStatus())).count(),products.stream().filter(product->ProductStatus.DRAFT.equals(product.getStatus())).count(),products.stream().filter(product->product.getStock()==0).count());}}
