package com.lbos.commercecustomer.service.impl; import com.lbos.commercecustomer.client.OrderLogisticsClient;import com.lbos.commercecustomer.dto.request.*;import com.lbos.commercecustomer.dto.response.*;import com.lbos.commercecustomer.entity.*;import com.lbos.commercecustomer.exception.*;import com.lbos.commercecustomer.mapper.CommerceMapper;import com.lbos.commercecustomer.repository.*;import com.lbos.commercecustomer.service.ReviewService;import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*; @Service public class ReviewServiceImpl implements ReviewService {private final CustomerReviewRepository repo;private final ProductRepository products;private final ContextSupport ctx;private final OrderLogisticsClient order;private final CommerceMapper map;private final FeignCallSupport feign;public ReviewServiceImpl(CustomerReviewRepository r,ProductRepository p,ContextSupport c,OrderLogisticsClient o,CommerceMapper m,FeignCallSupport g){repo=r;products=p;ctx=c;order=o;map=m;feign=g;}private CustomerReview getE(UUID id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Review not found"));}private void eligible(Long orderId,Long productId){var eligibility=feign.call("lbos-order",()->order.reviewEligibility(orderId,ctx.customer().getId(),productId));if(eligibility==null||!eligibility.eligible())throw new ForbiddenOperationException("Review is not permitted");}

  /**
   * Defense-in-depth alongside eligible(): the review's own customerId (set at creation from
   * the authenticated caller) must match the current caller before a mutation is allowed, so a
   * permissive S4 eligibility rule alone can never let someone edit or delete another
   * customer's review.
   */
  private void ownedByCaller(CustomerReview review){if(!review.getCustomerId().equals(ctx.customer().getId()))throw new ForbiddenOperationException("Review does not belong to the current customer");}

  private void refreshQualityFlag(Long productId){double average=Optional.ofNullable(repo.average(productId)).orElse(0d);long count=repo.countByProductId(productId);var product=products.findById(productId).orElseThrow(()->new ResourceNotFoundException("Product not found"));String flag=count>=5&&average>=4.5?"TRENDING":count>=5&&average<=2.0?"LOW_RATED":null;product.setQualityFlag(flag);products.save(product);}@Transactional public ReviewResponse create(ReviewRequest r){eligible(r.orderId(),r.productId());if(repo.existsByOrderIdAndProductId(r.orderId(),r.productId()))throw new DuplicateResourceException("Review already exists");var review=new CustomerReview();review.setOrderId(r.orderId());review.setProduct(products.findById(r.productId()).orElseThrow(()->new ResourceNotFoundException("Product not found")));review.setCustomerId(ctx.customer().getId());review.setRating(r.rating());review.setText(r.reviewText());var saved=repo.save(review);refreshQualityFlag(r.productId());return map.review(saved);}

  /**
   * Public read (GET /api/v1/reviews/{id} is permitAll() in SecurityConfig, matching
   * GET /api/v1/reviews search by productId) - must not require authentication or gate on
   * order-eligibility, which is a mutation-time concern only.
   */
  @Transactional(readOnly=true) public ReviewResponse get(UUID id){return map.review(getE(id));}

  /** rating is now applied as a DB-level filter (findByProductIdAndRating) instead of an in-memory post-filter, so pagination metadata is accurate. */
  @Transactional(readOnly=true) public PageResponse<ReviewResponse> search(Long productId,Short rating,int p,int z){if(productId==null)throw new BusinessValidationException("productId is required");var pageable=PageRequest.of(p,z,Sort.by(Sort.Direction.DESC,"createdAt"));var reviewPage=rating==null?repo.findByProductId(productId,pageable):repo.findByProductIdAndRating(productId,rating,pageable);return new PageResponse<>(reviewPage.map(map::review).getContent(),p,z,reviewPage.getTotalElements(),reviewPage.getTotalPages());}@Transactional public ReviewResponse update(UUID id,UpdateReviewRequest r){var review=getE(id);ownedByCaller(review);eligible(review.getOrderId(),review.getProduct().getId());review.setRating(r.rating());review.setText(r.reviewText());var saved=repo.save(review);refreshQualityFlag(saved.getProduct().getId());return map.review(saved);}@Transactional public void delete(UUID id){var review=getE(id);ownedByCaller(review);eligible(review.getOrderId(),review.getProduct().getId());Long productId=review.getProduct().getId();repo.delete(review);refreshQualityFlag(productId);}@Transactional(readOnly=true) public RatingSummaryResponse rating(Long productId){double averageRating=Optional.ofNullable(repo.average(productId)).orElse(0d);var allReviews=repo.findByProductId(productId,Pageable.unpaged()).getContent();var distribution=new HashMap<Short,Long>();for(short star=1;star<=5;star++){short currentStar=star;distribution.put(star,allReviews.stream().filter(review->review.getRating()==currentStar).count());}return new RatingSummaryResponse(productId,averageRating,repo.countByProductId(productId),distribution);}

  /** Lazily computed, only on demand (shop-card expand) - see RetailerRatingSummaryResponse. */
  @Transactional(readOnly=true) public RetailerRatingSummaryResponse retailerRating(UUID retailerId){double average=Optional.ofNullable(repo.averageByRetailerId(retailerId)).orElse(0d);return new RetailerRatingSummaryResponse(retailerId,average,repo.countByRetailerId(retailerId));}

  @Transactional(readOnly=true) public com.lbos.commercecustomer.dto.client.order.ReviewEligibilityResponse eligibility(Long productId){var customerId=ctx.customer().getId();var result=feign.call("lbos-order",()->order.eligibleOrderForReview(customerId,productId));return result!=null?result:new com.lbos.commercecustomer.dto.client.order.ReviewEligibilityResponse(false,null,customerId,productId,"LOOKUP_FAILED");}}
